<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
    <line>
      <![CDATA[ERROR : This is error]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[INFO : This is not]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="27" started-at="2019-11-14T10:32:42Z" finished-at="2019-11-14T10:32:42Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27" started-at="2019-11-14T10:32:42Z" finished-at="2019-11-14T10:32:42Z">
      <class name="com.test.VerifyVsValidate">
        <test-method status="PASS" signature="one()[pri:0, instance:com.test.VerifyVsValidate@4678c730]" name="one" duration-ms="10" started-at="2019-11-14T16:02:42Z" finished-at="2019-11-14T16:02:42Z">
          <reporter-output>
            <line>
              <![CDATA[ERROR : This is error]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[INFO : This is not]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
          </reporter-output>
        </test-method> <!-- one -->
        <test-method status="PASS" signature="testRegistrationNONDataDriven()[pri:0, instance:com.test.VerifyVsValidate@4678c730]" name="testRegistrationNONDataDriven" duration-ms="1" started-at="2019-11-14T16:02:42Z" finished-at="2019-11-14T16:02:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRegistrationNONDataDriven -->
        <test-method status="FAIL" signature="two()[pri:0, instance:com.test.VerifyVsValidate@4678c730]" name="two" duration-ms="1" started-at="2019-11-14T16:02:42Z" finished-at="2019-11-14T16:02:42Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<5> but was:<6>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<5> but was:<6>
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.failNotEquals(Assert.java:282)
	at junit.framework.Assert.assertEquals(Assert.java:64)
	at junit.framework.Assert.assertEquals(Assert.java:201)
	at junit.framework.Assert.assertEquals(Assert.java:207)
	at com.test.VerifyVsValidate.two(VerifyVsValidate.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- two -->
      </class> <!-- com.test.VerifyVsValidate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
